# Generated by Django 2.0.2 on 2018-02-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='envdata.Population'),
        ),
    ]
