# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlateCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('col', models.IntegerField()),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode.Barcode')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plate.Plate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='platecell',
            unique_together=set([('plate', 'row', 'col')]),
        ),
    ]
