# Generated by Django 2.0.2 on 2018-02-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platecell',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='barcode.Barcode'),
        ),
        migrations.AlterField(
            model_name='platecell',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plate.Plate'),
        ),
    ]
